import { DefaultTheme } from '@react-navigation/native';

// Map the custom theme colors to react-native-paper's theme structure
export const MapToPaperTheme = (colors: any) => ({
  ...DefaultTheme,
  colors: {
    primary: colors.primary,
    background: colors.background,
    surface: colors.surface,
    text: colors.onSurface,
    onPrimary: colors.onPrimary,
    onBackground: colors.onBackground,
    onSurface: colors.onSurface,
    primaryContainer: colors.primaryContainer,
    onPrimaryContainer: colors.onPrimaryContainer,
    secondary: colors.secondary,
    onSecondary: colors.onSecondary,
    secondaryContainer: colors.secondaryContainer,
    onSecondaryContainer: colors.onSecondaryContainer,
    tertiary: colors.tertiary,
    onTertiary: colors.onTertiary,
    tertiaryContainer: colors.tertiaryContainer,
    onTertiaryContainer: colors.onTertiaryContainer,
    error: colors.error,
    onError: colors.onError,
    errorContainer: colors.errorContainer,
    onErrorContainer: colors.onErrorContainer,
    surfaceVariant: colors.surfaceVariant,
    onSurfaceVariant: colors.onSurfaceVariant,
    outline: colors.outline,
    shadow: colors.shadow,
    scrim: colors.scrim,
    card: colors.surface,
    border: colors.surfaceVariant,
    notification: colors.primary,
    inverseSurface: colors.inverseSurface,
    inverseOnSurface: colors.inverseOnSurface,
    inversePrimary: colors.inversePrimary,
  },
});
