export const genres = [
  {
    id: 1,
    genre: 'Action',
    image: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16498-73IhOXpJZiMF.jpg',
  },
  {
    id: 2,
    genre: 'Adventure',
    image: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11061-NpIIobuQNbJW.png',
  },
  {
    id: 3,
    genre: 'Cars',
    image:
      'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx143327-6gv1QzquNg2o.png',
  },
  {
    id: 4,
    genre: 'Comedy',
    image: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx918-hRbQHIkRUebX.jpg',
  },
  {
    id: 5,
    genre: 'Dementia',
    image: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx98460-bLtH2c3jd6sV.png',
  },
  {
    id: 6,
    genre: 'Demons',
    image:
      'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-WBsBl0ClmgYL.jpg',
  },
  { id: 7, genre: 'Drama', image: '' },
  { id: 8, genre: 'Ecchi', image: '' },
  { id: 9, genre: 'Fantasy', image: '' },
  { id: 10, genre: 'Game', image: '' },
  { id: 11, genre: 'Harem', image: '' },
  { id: 12, genre: 'Historical', image: '' },
  { id: 13, genre: 'Horror', image: '' },
  { id: 14, genre: 'Isekai', image: '' },
  { id: 15, genre: 'Josei', image: '' },
  { id: 16, genre: 'Kids', image: '' },
  { id: 17, genre: 'Magic', image: '' },
  { id: 18, genre: 'Martial Arts', image: '' },
  { id: 19, genre: 'Mecha', image: '' },
  { id: 20, genre: 'Military', image: '' },
  { id: 21, genre: 'Music', image: '' },
  { id: 22, genre: 'Mystery', image: '' },
  { id: 23, genre: 'Parody', image: '' },
  { id: 24, genre: 'Police', image: '' },
  { id: 25, genre: 'Psychological', image: '' },
  { id: 26, genre: 'Romance', image: '' },
  { id: 27, genre: 'Samurai', image: '' },
  { id: 28, genre: 'School', image: '' },
  { id: 29, genre: 'Sci-Fi', image: '' },
  { id: 30, genre: 'Seinen', image: '' },
  { id: 31, genre: 'Shoujo', image: '' },
  { id: 32, genre: 'Shoujo Ai', image: '' },
  { id: 33, genre: 'Shounen', image: '' },
  { id: 34, genre: 'Shounen Ai', image: '' },
  { id: 35, genre: 'Slice of Life', image: '' },
  { id: 36, genre: 'Space', image: '' },
  { id: 37, genre: 'Sports', image: '' },
  { id: 38, genre: 'Super Power', image: '' },
  { id: 39, genre: 'Supernatural', image: '' },
  { id: 40, genre: 'Thriller', image: '' },
  { id: 41, genre: 'Vampire', image: '' },
];
